import { NextResponse } from "next/server";

interface AirportData {
  iata: string;
  city: string;
  name: string;
  skyId: string;
  entityId: string;
}

const BRAZIL_AIRPORTS: AirportData[] = [
  {
    iata: "GRU",
    city: "São Paulo",
    name: "Guarulhos Internacional",
    skyId: "GRU",
    entityId: "95565072",
  },
  {
    iata: "CGH",
    city: "São Paulo",
    name: "Congonhas",
    skyId: "CGH",
    entityId: "27544008",
  },
  {
    iata: "BSB",
    city: "Brasília",
    name: "Presidente Juscelino Kubitschek",
    skyId: "BSB",
    entityId: "27543787",
  },
  {
    iata: "GIG",
    city: "Rio de Janeiro",
    name: "Galeão Internacional",
    skyId: "GIG",
    entityId: "27539791",
  },
  {
    iata: "VCP",
    city: "Campinas",
    name: "Viracopos",
    skyId: "VCP",
    entityId: "27542289",
  },
  {
    iata: "SDU",
    city: "Rio de Janeiro",
    name: "Santos Dumont",
    skyId: "SDU",
    entityId: "27539793",
  },
  {
    iata: "CNF",
    city: "Belo Horizonte",
    name: "Confins Internacional",
    skyId: "CNF",
    entityId: "27541738",
  },
  {
    iata: "REC",
    city: "Recife",
    name: "Guararapes Internacional",
    skyId: "REC",
    entityId: "27539714",
  },
  {
    iata: "SSA",
    city: "Salvador",
    name: "Deputado Luís Eduardo Magalhães",
    skyId: "SSA",
    entityId: "27539824",
  },
  {
    iata: "POA",
    city: "Porto Alegre",
    name: "Salgado Filho",
    skyId: "POA",
    entityId: "27539712",
  },
  {
    iata: "FOR",
    city: "Fortaleza",
    name: "Pinto Martins",
    skyId: "FOR",
    entityId: "27539324",
  },
  {
    iata: "CWB",
    city: "Curitiba",
    name: "Afonso Pena",
    skyId: "CWB",
    entityId: "27542456",
  },
  {
    iata: "FLN",
    city: "Florianópolis",
    name: "Hercílio Luz",
    skyId: "FLN",
    entityId: "27543242",
  },
  {
    iata: "BEL",
    city: "Belém",
    name: "Val-de-Cans Internacional",
    skyId: "BEL",
    entityId: "27541708",
  },
  {
    iata: "GYN",
    city: "Goiânia",
    name: "Santa Genoveva",
    skyId: "GYN",
    entityId: "27543414",
  },
  {
    iata: "VIX",
    city: "Vitória",
    name: "Eurico de Aguiar Salles",
    skyId: "VIX",
    entityId: "27540201",
  },
  {
    iata: "MAO",
    city: "Manaus",
    name: "Eduardo Gomes Internacional",
    skyId: "MAO",
    entityId: "27539462",
  },
  {
    iata: "CGB",
    city: "Cuiabá",
    name: "Marechal Rondon",
    skyId: "CGB",
    entityId: "27542306",
  },
  {
    iata: "MCZ",
    city: "Maceió",
    name: "Zumbi dos Palmares",
    skyId: "MCZ",
    entityId: "27539450",
  },
  {
    iata: "NAT",
    city: "Natal",
    name: "Governador Aluízio Alves",
    skyId: "NAT",
    entityId: "95673473",
  },
  {
    iata: "NVT",
    city: "Navegantes",
    name: "Ministro Victor Konder",
    skyId: "NVT",
    entityId: "27545460",
  },
  {
    iata: "UDI",
    city: "Uberlândia",
    name: "Ten. Cel. Aviador César Bombonato",
    skyId: "UDI",
    entityId: "27540061",
  },
  {
    iata: "CGR",
    city: "Campo Grande",
    name: "Internacional de Campo Grande",
    skyId: "CGR",
    entityId: "27542294",
  },
  {
    iata: "JPA",
    city: "João Pessoa",
    name: "Presidente Castro Pinto",
    skyId: "JPA",
    entityId: "27539384",
  },
  {
    iata: "SLZ",
    city: "São Luís",
    name: "Marechal Cunha Machado",
    skyId: "SLZ",
    entityId: "27539893",
  },
  {
    iata: "THE",
    city: "Teresina",
    name: "Senador Petrônio Portella",
    skyId: "THE",
    entityId: "27539958",
  },
  {
    iata: "AJU",
    city: "Aracaju",
    name: "Santa Maria",
    skyId: "AJU",
    entityId: "27541481",
  },
  {
    iata: "LDB",
    city: "Londrina",
    name: "Governador José Richa",
    skyId: "LDB",
    entityId: "27544602",
  },
  {
    iata: "RAO",
    city: "Ribeirão Preto",
    name: "Leite Lopes",
    skyId: "RAO",
    entityId: "27546416",
  },
  {
    iata: "PVH",
    city: "Porto Velho",
    name: "Governador Jorge Teixeira de Oliveira",
    skyId: "PVH",
    entityId: "27539704",
  },
  {
    iata: "SJP",
    city: "São José do Rio Preto",
    name: "Professor Eribelto Manoel Reino",
    skyId: "SJP",
    entityId: "27547012",
  },
  {
    iata: "MGF",
    city: "Maringá",
    name: "Sílvio Name Júnior",
    skyId: "MGF",
    entityId: "27545046",
  },
  {
    iata: "PMW",
    city: "Palmas",
    name: "Brigadeiro Lysias Rodrigues",
    skyId: "PMW",
    entityId: "27539665",
  },
  {
    iata: "IOS",
    city: "Ilhéus",
    name: "Jorge Amado",
    skyId: "IOS",
    entityId: "27539352",
  },
  {
    iata: "BPS",
    city: "Porto Seguro",
    name: "Internacional de Porto Seguro",
    skyId: "BPS",
    entityId: "27541819",
  },
  {
    iata: "XAP",
    city: "Chapecó",
    name: "Serafim Enoss Bertaso",
    skyId: "XAP",
    entityId: "27540296",
  },
  {
    iata: "JDO",
    city: "Juazeiro do Norte",
    name: "Orlando Bezerra de Menezes",
    skyId: "JDO",
    entityId: "27539371",
  },
  {
    iata: "STM",
    city: "Santarém",
    name: "Maestro Wilson Fonseca",
    skyId: "STM",
    entityId: "27539832",
  },
  {
    iata: "BVB",
    city: "Boa Vista",
    name: "Atlas Brasil Cantanhede",
    skyId: "BVB",
    entityId: "27541842",
  },
  {
    iata: "RBR",
    city: "Rio Branco",
    name: "Plácido de Castro",
    skyId: "RBR",
    entityId: "27539710",
  },
  {
    iata: "MOC",
    city: "Montes Claros",
    name: "Mário Ribeiro",
    skyId: "MOC",
    entityId: "27539493",
  },
  {
    iata: "IMP",
    city: "Imperatriz",
    name: "Prefeito Renato Moreira",
    skyId: "IMP",
    entityId: "27539344",
  },
  {
    iata: "PET",
    city: "Pelotas",
    name: "Internacional de Pelotas",
    skyId: "PET",
    entityId: "27539652",
  },
  {
    iata: "CXJ",
    city: "Caxias do Sul",
    name: "Hugo Cantergiani",
    skyId: "CXJ",
    entityId: "27542513",
  },
  {
    iata: "CPV",
    city: "Campina Grande",
    name: "Presidente João Suassuna",
    skyId: "CPV",
    entityId: "27542291",
  },
  {
    iata: "VDC",
    city: "Vitória da Conquista",
    name: "Glauber Rocha",
    skyId: "VDC",
    entityId: "123473133",
  },
  {
    iata: "PHB",
    city: "Parnaíba",
    name: "Prefeito Dr. João Silva Filho",
    skyId: "PHB",
    entityId: "27539655",
  },
  {
    iata: "CRCl",
    city: "Criciúma",
    name: "Diomício Freitas",
    skyId: "CCM",
    entityId: "27542173",
  },
  {
    iata: "JOI",
    city: "Joinville",
    name: "Lauro Carneiro de Loyola",
    skyId: "JOI",
    entityId: "27544065",
  },
  {
    iata: "FEN",
    city: "Fernando de Noronha",
    name: "Governador Carlos Wilson",
    skyId: "FEN",
    entityId: "27543166",
  },
];

const WORLD_AIRPORTS: AirportData[] = [
  {
    iata: "ATL",
    city: "Atlanta",
    name: "Hartsfield-Jackson Atlanta",
    skyId: "ATL",
    entityId: "27536630",
  },
  {
    iata: "PEK",
    city: "Pequim",
    name: "Beijing Capital International",
    skyId: "PEK",
    entityId: "27539193",
  },
  {
    iata: "DXB",
    city: "Dubai",
    name: "Dubai International",
    skyId: "DXB",
    entityId: "27543026",
  },
  {
    iata: "LAX",
    city: "Los Angeles",
    name: "Los Angeles International",
    skyId: "LAX",
    entityId: "27536675",
  },
  {
    iata: "HND",
    city: "Tóquio",
    name: "Haneda Airport",
    skyId: "HND",
    entityId: "27543940",
  },
  {
    iata: "ORD",
    city: "Chicago",
    name: "O'Hare International",
    skyId: "ORD",
    entityId: "27536622",
  },
  {
    iata: "LHR",
    city: "Londres",
    name: "Heathrow Airport",
    skyId: "LHR",
    entityId: "26192131",
  },
  {
    iata: "PVG",
    city: "Xangai",
    name: "Pudong International",
    skyId: "PVG",
    entityId: "27539839",
  },
  {
    iata: "CDG",
    city: "Paris",
    name: "Charles de Gaulle",
    skyId: "CDG",
    entityId: "27542618",
  },
  {
    iata: "DFW",
    city: "Dallas",
    name: "Dallas/Fort Worth International",
    skyId: "DFW",
    entityId: "27536601",
  },
  {
    iata: "CAN",
    city: "Guangzhou",
    name: "Baiyun International",
    skyId: "CAN",
    entityId: "27539276",
  },
  {
    iata: "AMS",
    city: "Amsterdã",
    name: "Schiphol Airport",
    skyId: "AMS",
    entityId: "27541459",
  },
  {
    iata: "HKG",
    city: "Hong Kong",
    name: "Hong Kong International",
    skyId: "HKG",
    entityId: "27543943",
  },
  {
    iata: "ICN",
    city: "Seul",
    name: "Incheon International",
    skyId: "ICN",
    entityId: "27543997",
  },
  {
    iata: "FRA",
    city: "Frankfurt",
    name: "Frankfurt Airport",
    skyId: "FRA",
    entityId: "27543310",
  },
  {
    iata: "DEN",
    city: "Denver",
    name: "Denver International",
    skyId: "DEN",
    entityId: "27536643",
  },
  {
    iata: "DEL",
    city: "Nova Deli",
    name: "Indira Gandhi International",
    skyId: "DEL",
    entityId: "27542880",
  },
  {
    iata: "SIN",
    city: "Singapura",
    name: "Changi Airport",
    skyId: "SIN",
    entityId: "27547035",
  },
  {
    iata: "BKK",
    city: "Bangcoc",
    name: "Suvarnabhumi Airport",
    skyId: "BKK",
    entityId: "27541743",
  },
  {
    iata: "JFK",
    city: "Nova York",
    name: "John F. Kennedy International",
    skyId: "JFK",
    entityId: "95565058",
  },
  {
    iata: "KUL",
    city: "Kuala Lumpur",
    name: "Kuala Lumpur International",
    skyId: "KUL",
    entityId: "27544254",
  },
  {
    iata: "MAD",
    city: "Madri",
    name: "Adolfo Suárez Madrid-Barajas",
    skyId: "MAD",
    entityId: "27544831",
  },
  {
    iata: "SFO",
    city: "São Francisco",
    name: "San Francisco International",
    skyId: "SFO",
    entityId: "27536712",
  },
  {
    iata: "CTU",
    city: "Chengdu",
    name: "Shuangliu International",
    skyId: "CTU",
    entityId: "27542473",
  },
  {
    iata: "SZX",
    city: "Shenzhen",
    name: "Bao'an International",
    skyId: "SZX",
    entityId: "27547228",
  },
  {
    iata: "MCO",
    city: "Orlando",
    name: "Orlando International",
    skyId: "MCO",
    entityId: "27536688",
  },
  {
    iata: "LAS",
    city: "Las Vegas",
    name: "Harry Reid International",
    skyId: "LAS",
    entityId: "27536657",
  },
  {
    iata: "BCN",
    city: "Barcelona",
    name: "El Prat Airport",
    skyId: "BCN",
    entityId: "27541645",
  },
  {
    iata: "YYZ",
    city: "Toronto",
    name: "Pearson International",
    skyId: "YYZ",
    entityId: "27537302",
  },
  {
    iata: "MEX",
    city: "Cidade do México",
    name: "Benito Juárez International",
    skyId: "MEX",
    entityId: "27537166",
  },
  {
    iata: "KMG",
    city: "Kunming",
    name: "Changshui International",
    skyId: "KMG",
    entityId: "27544243",
  },
  {
    iata: "SEA",
    city: "Seattle",
    name: "Seattle-Tacoma International",
    skyId: "SEA",
    entityId: "27536720",
  },
  {
    iata: "BOM",
    city: "Mumbai",
    name: "Chhatrapati Shivaji Maharaj",
    skyId: "BOM",
    entityId: "27541748",
  },
  {
    iata: "LGW",
    city: "Londres",
    name: "Gatwick Airport",
    skyId: "LGW",
    entityId: "26192132",
  },
  {
    iata: "EWR",
    city: "Nova York",
    name: "Newark Liberty International",
    skyId: "EWR",
    entityId: "95565059",
  },
  {
    iata: "MNL",
    city: "Manila",
    name: "Ninoy Aquino International",
    skyId: "MNL",
    entityId: "27539527",
  },
  {
    iata: "NRT",
    city: "Tóquio",
    name: "Narita International",
    skyId: "NRT",
    entityId: "27545624",
  },
  {
    iata: "MSP",
    city: "Minneapolis",
    name: "Minneapolis-Saint Paul",
    skyId: "MSP",
    entityId: "27536680",
  },
  {
    iata: "DOH",
    city: "Doha",
    name: "Hamad International",
    skyId: "DOH",
    entityId: "27542930",
  },
  {
    iata: "MIA",
    city: "Miami",
    name: "Miami International",
    skyId: "MIA",
    entityId: "27536640",
  },
  {
    iata: "PHX",
    city: "Phoenix",
    name: "Sky Harbor International",
    skyId: "PHX",
    entityId: "27536696",
  },
  {
    iata: "SYD",
    city: "Sydney",
    name: "Kingsford Smith Airport",
    skyId: "SYD",
    entityId: "27547167",
  },
  {
    iata: "IAH",
    city: "Houston",
    name: "George Bush Intercontinental",
    skyId: "IAH",
    entityId: "27536649",
  },
  {
    iata: "SVO",
    city: "Moscou",
    name: "Sheremetyevo International",
    skyId: "SVO",
    entityId: "27547134",
  },
  {
    iata: "MUC",
    city: "Munique",
    name: "Munich Airport",
    skyId: "MUC",
    entityId: "27545041",
  },
  {
    iata: "CGK",
    city: "Jacarta",
    name: "Soekarno-Hatta International",
    skyId: "CGK",
    entityId: "27542408",
  },
  {
    iata: "XIY",
    city: "Xi'an",
    name: "Xianyang International",
    skyId: "XIY",
    entityId: "27540410",
  },
  {
    iata: "FCO",
    city: "Roma",
    name: "Leonardo da Vinci-Fiumicino",
    skyId: "FCO",
    entityId: "27543160",
  },
  {
    iata: "LIS",
    city: "Lisboa",
    name: "Humberto Delgado Airport",
    skyId: "LIS",
    entityId: "27544618",
  },
  {
    iata: "GVA",
    city: "Genebra",
    name: "Geneva International",
    skyId: "GVA",
    entityId: "27543405",
  },
];

// União total de todos os aeroportos para filtragem de memória
const ALL_AIRPORTS = [...BRAZIL_AIRPORTS, ...WORLD_AIRPORTS];

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const query = searchParams.get("query")?.trim().toLowerCase() || "";

  // Resposta vazia imediata se o termo for menor que 2 letras
  if (query.length < 2) {
    return NextResponse.json([]);
  }

  // Filtragem ultra-rápida na memória do servidor
  const filtered = ALL_AIRPORTS.filter(
    (airport) =>
      airport.iata.toLowerCase().includes(query) ||
      airport.city.toLowerCase().includes(query) ||
      airport.name.toLowerCase().includes(query),
  );

  return NextResponse.json(filtered);
}
